# network-install
# https://github.com/gucci-on-fleek/network-install
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff
when:
  - event: [push, tag, pull_request]
    branch: master

steps:
  - name: Build
    image: maxchernoff.ca/tex-gcc:latest
    pull: true
    commands:
      - set -euxo pipefail
      - pushd ./source/c/
      - make -j4
      - popd
      - export TEXMFHOME=$(realpath ./texmf)
      - l3build doc
      - l3build bundle

  - name: Release
    when:
      event: tag
    image: docker.io/woodpeckerci/plugin-release
    settings:
      overwrite: false
      title: ./release.title
      files:
        - network-install-*.tds.zip
        - network-install-*.ctan.zip
      file-exists: fail
      api_key:
        from_secret: GITHUB_TOKEN

  - name: Email on failure
    image: docker.io/deblan/woodpecker-email:latest
    when:
        status:
          - failure
    settings:
        level: failure
        dsn:
            from_secret: EMAIL_DSN
        from:
            address: "woodpecker@noreply.maxchernoff.ca"
        recipients:
          - "server-status@maxchernoff.ca"
        recipients_only: true
        content:
            subject: >
                [{{ pipeline.status }}]
                {{ repo.full_name }}
                ({{ commit.branch }} - {{ commit.sha[0:8] }})"
            body: |
                {{ commit.sha }}<br>
                {{ pipeline.status }}<br>
                {{ commit.author_email }}<br>
