// Types
typedef void CURL;
typedef enum {
    CURLE_OK = 0,
    CURLE_UNSUPPORTED_PROTOCOL,
    CURLE_FAILED_INIT,
    CURLE_URL_MALFORMAT,
    CURLE_NOT_BUILT_IN,
    CURLE_COULDNT_RESOLVE_PROXY,
    CURLE_COULDNT_RESOLVE_HOST,
    CURLE_COULDNT_CONNECT,
    CURLE_WEIRD_SERVER_REPLY,
    CURLE_REMOTE_ACCESS_DENIED,
    CURLE_FTP_ACCEPT_FAILED,
    CURLE_FTP_WEIRD_PASS_REPLY,
    CURLE_FTP_ACCEPT_TIMEOUT,
    CURLE_FTP_WEIRD_PASV_REPLY,
    CURLE_FTP_WEIRD_227_FORMAT,
    CURLE_FTP_CANT_GET_HOST,
    CURLE_HTTP2,
    CURLE_FTP_COULDNT_SET_TYPE,
    CURLE_PARTIAL_FILE,
    CURLE_FTP_COULDNT_RETR_FILE,
    CURLE_OBSOLETE20,
    CURLE_QUOTE_ERROR,
    CURLE_HTTP_RETURNED_ERROR,
    CURLE_WRITE_ERROR,
    CURLE_OBSOLETE24,
    CURLE_UPLOAD_FAILED,
    CURLE_READ_ERROR,
    CURLE_OUT_OF_MEMORY,
    CURLE_OPERATION_TIMEDOUT,
    CURLE_OBSOLETE29,
    CURLE_FTP_PORT_FAILED,
    CURLE_FTP_COULDNT_USE_REST,
    CURLE_OBSOLETE32,
    CURLE_RANGE_ERROR,
    CURLE_OBSOLETE34,
    CURLE_SSL_CONNECT_ERROR,
    CURLE_BAD_DOWNLOAD_RESUME,
    CURLE_FILE_COULDNT_READ_FILE,
    CURLE_LDAP_CANNOT_BIND,
    CURLE_LDAP_SEARCH_FAILED,
    CURLE_OBSOLETE40,
    CURLE_OBSOLETE41,
    CURLE_ABORTED_BY_CALLBACK,
    CURLE_BAD_FUNCTION_ARGUMENT,
    CURLE_OBSOLETE44,
    CURLE_INTERFACE_FAILED,
    CURLE_OBSOLETE46,
    CURLE_TOO_MANY_REDIRECTS,
    CURLE_UNKNOWN_OPTION,
    CURLE_SETOPT_OPTION_SYNTAX,
    CURLE_OBSOLETE50,
    CURLE_OBSOLETE51,
    CURLE_GOT_NOTHING,
    CURLE_SSL_ENGINE_NOTFOUND,
    CURLE_SSL_ENGINE_SETFAILED,
    CURLE_SEND_ERROR,
    CURLE_RECV_ERROR,
    CURLE_OBSOLETE57,
    CURLE_SSL_CERTPROBLEM,
    CURLE_SSL_CIPHER,
    CURLE_PEER_FAILED_VERIFICATION,
    CURLE_BAD_CONTENT_ENCODING,
    CURLE_OBSOLETE62,
    CURLE_FILESIZE_EXCEEDED,
    CURLE_USE_SSL_FAILED,
    CURLE_SEND_FAIL_REWIND,
    CURLE_SSL_ENGINE_INITFAILED,
    CURLE_LOGIN_DENIED,
    CURLE_TFTP_NOTFOUND,
    CURLE_TFTP_PERM,
    CURLE_REMOTE_DISK_FULL,
    CURLE_TFTP_ILLEGAL,
    CURLE_TFTP_UNKNOWNID,
    CURLE_REMOTE_FILE_EXISTS,
    CURLE_TFTP_NOSUCHUSER,
    CURLE_OBSOLETE75,
    CURLE_OBSOLETE76,
    CURLE_SSL_CACERT_BADFILE,
    CURLE_REMOTE_FILE_NOT_FOUND,
    CURLE_SSH,
    CURLE_SSL_SHUTDOWN_FAILED,
    CURLE_AGAIN,
    CURLE_SSL_CRL_BADFILE,
    CURLE_SSL_ISSUER_ERROR,
    CURLE_FTP_PRET_FAILED,
    CURLE_RTSP_CSEQ_ERROR,
    CURLE_RTSP_SESSION_ERROR,
    CURLE_FTP_BAD_FILE_LIST,
    CURLE_CHUNK_FAILED,
    CURLE_NO_CONNECTION_AVAILABLE,
    CURLE_SSL_PINNEDPUBKEYNOTMATCH,
    CURLE_SSL_INVALIDCERTSTATUS,
    CURLE_HTTP2_STREAM,
    CURLE_RECURSIVE_API_CALL,
    CURLE_AUTH_ERROR,
    CURLE_HTTP3,
    CURLE_QUIC_CONNECT_ERROR,
    CURLE_PROXY,
    CURLE_SSL_CLIENTCERT,
    CURLE_UNRECOVERABLE_POLL,
    CURLE_TOO_LARGE,
    CURLE_ECH_REQUIRED,
} CURLcode;

typedef enum {
    CURLOPT_WRITEDATA = 10001,
    CURLOPT_URL,
    CURLOPT_PORT = 3,
    CURLOPT_PROXY = 10004,
    CURLOPT_USERPWD,
    CURLOPT_PROXYUSERPWD,
    CURLOPT_RANGE,
    CURLOPT_READDATA = 10009,
    CURLOPT_ERRORBUFFER,
    CURLOPT_WRITEFUNCTION = 20011,
    CURLOPT_READFUNCTION,
    CURLOPT_TIMEOUT = 13,
    CURLOPT_INFILESIZE,
    CURLOPT_POSTFIELDS = 10015,
    CURLOPT_REFERER,
    CURLOPT_FTPPORT,
    CURLOPT_USERAGENT,
    CURLOPT_LOW_SPEED_LIMIT = 19,
    CURLOPT_LOW_SPEED_TIME,
    CURLOPT_RESUME_FROM,
    CURLOPT_COOKIE = 10022,
    CURLOPT_HTTPHEADER,
    CURLOPT_HTTPPOST,
    CURLOPT_SSLCERT,
    CURLOPT_KEYPASSWD,
    CURLOPT_CRLF = 27,
    CURLOPT_QUOTE = 10028,
    CURLOPT_HEADERDATA,
    CURLOPT_COOKIEFILE = 10031,
    CURLOPT_SSLVERSION = 32,
    CURLOPT_TIMECONDITION,
    CURLOPT_TIMEVALUE,
    CURLOPT_CUSTOMREQUEST = 10036,
    CURLOPT_STDERR,
    CURLOPT_POSTQUOTE = 10039,
    CURLOPT_VERBOSE = 41,
    CURLOPT_HEADER,
    CURLOPT_NOPROGRESS,
    CURLOPT_NOBODY,
    CURLOPT_FAILONERROR,
    CURLOPT_UPLOAD,
    CURLOPT_POST,
    CURLOPT_DIRLISTONLY,
    CURLOPT_APPEND = 50,
    CURLOPT_NETRC,
    CURLOPT_FOLLOWLOCATION,
    CURLOPT_TRANSFERTEXT,
    CURLOPT_PUT,
    CURLOPT_PROGRESSFUNCTION = 20056,
    CURLOPT_XFERINFODATA = 10057,
    CURLOPT_AUTOREFERER = 58,
    CURLOPT_PROXYPORT,
    CURLOPT_POSTFIELDSIZE,
    CURLOPT_HTTPPROXYTUNNEL,
    CURLOPT_INTERFACE = 10062,
    CURLOPT_KRBLEVEL,
    CURLOPT_SSL_VERIFYPEER = 64,
    CURLOPT_CAINFO = 10065,
    CURLOPT_MAXREDIRS = 68,
    CURLOPT_FILETIME,
    CURLOPT_TELNETOPTIONS = 10070,
    CURLOPT_MAXCONNECTS = 71,
    CURLOPT_FRESH_CONNECT = 74,
    CURLOPT_FORBID_REUSE,
    CURLOPT_RANDOM_FILE = 10076,
    CURLOPT_EGDSOCKET,
    CURLOPT_CONNECTTIMEOUT = 78,
    CURLOPT_HEADERFUNCTION = 20079,
    CURLOPT_HTTPGET = 80,
    CURLOPT_SSL_VERIFYHOST,
    CURLOPT_COOKIEJAR = 10082,
    CURLOPT_SSL_CIPHER_LIST,
    CURLOPT_HTTP_VERSION = 84,
    CURLOPT_FTP_USE_EPSV,
    CURLOPT_SSLCERTTYPE = 10086,
    CURLOPT_SSLKEY,
    CURLOPT_SSLKEYTYPE,
    CURLOPT_SSLENGINE,
    CURLOPT_SSLENGINE_DEFAULT = 90,
    CURLOPT_DNS_USE_GLOBAL_CACHE,
    CURLOPT_DNS_CACHE_TIMEOUT,
    CURLOPT_PREQUOTE = 10093,
    CURLOPT_DEBUGFUNCTION = 20094,
    CURLOPT_DEBUGDATA = 10095,
    CURLOPT_COOKIESESSION = 96,
    CURLOPT_CAPATH = 10097,
    CURLOPT_BUFFERSIZE = 98,
    CURLOPT_NOSIGNAL,
    CURLOPT_SHARE = 10100,
    CURLOPT_PROXYTYPE = 101,
    CURLOPT_ACCEPT_ENCODING = 10102,
    CURLOPT_PRIVATE,
    CURLOPT_HTTP200ALIASES,
    CURLOPT_UNRESTRICTED_AUTH = 105,
    CURLOPT_FTP_USE_EPRT,
    CURLOPT_HTTPAUTH,
    CURLOPT_SSL_CTX_FUNCTION = 20108,
    CURLOPT_SSL_CTX_DATA = 10109,
    CURLOPT_FTP_CREATE_MISSING_DIRS = 110,
    CURLOPT_PROXYAUTH,
    CURLOPT_SERVER_RESPONSE_TIMEOUT,
    CURLOPT_IPRESOLVE,
    CURLOPT_MAXFILESIZE,
    CURLOPT_INFILESIZE_LARGE = 30115,
    CURLOPT_RESUME_FROM_LARGE,
    CURLOPT_MAXFILESIZE_LARGE,
    CURLOPT_NETRC_FILE = 10118,
    CURLOPT_USE_SSL = 119,
    CURLOPT_POSTFIELDSIZE_LARGE = 30120,
    CURLOPT_TCP_NODELAY = 121,
    CURLOPT_FTPSSLAUTH = 129,
    CURLOPT_IOCTLFUNCTION = 20130,
    CURLOPT_IOCTLDATA = 10131,
    CURLOPT_FTP_ACCOUNT = 10134,
    CURLOPT_COOKIELIST,
    CURLOPT_IGNORE_CONTENT_LENGTH = 136,
    CURLOPT_FTP_SKIP_PASV_IP,
    CURLOPT_FTP_FILEMETHOD,
    CURLOPT_LOCALPORT,
    CURLOPT_LOCALPORTRANGE,
    CURLOPT_CONNECT_ONLY,
    CURLOPT_CONV_FROM_NETWORK_FUNCTION = 20142,
    CURLOPT_CONV_TO_NETWORK_FUNCTION,
    CURLOPT_CONV_FROM_UTF8_FUNCTION,
    CURLOPT_MAX_SEND_SPEED_LARGE = 30145,
    CURLOPT_MAX_RECV_SPEED_LARGE,
    CURLOPT_FTP_ALTERNATIVE_TO_USER = 10147,
    CURLOPT_SOCKOPTFUNCTION = 20148,
    CURLOPT_SOCKOPTDATA = 10149,
    CURLOPT_SSL_SESSIONID_CACHE = 150,
    CURLOPT_SSH_AUTH_TYPES,
    CURLOPT_SSH_PUBLIC_KEYFILE = 10152,
    CURLOPT_SSH_PRIVATE_KEYFILE,
    CURLOPT_FTP_SSL_CCC = 154,
    CURLOPT_TIMEOUT_MS,
    CURLOPT_CONNECTTIMEOUT_MS,
    CURLOPT_HTTP_TRANSFER_DECODING,
    CURLOPT_HTTP_CONTENT_DECODING,
    CURLOPT_NEW_FILE_PERMS,
    CURLOPT_NEW_DIRECTORY_PERMS,
    CURLOPT_POSTREDIR,
    CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 = 10162,
    CURLOPT_OPENSOCKETFUNCTION = 20163,
    CURLOPT_OPENSOCKETDATA = 10164,
    CURLOPT_COPYPOSTFIELDS,
    CURLOPT_PROXY_TRANSFER_MODE = 166,
    CURLOPT_SEEKFUNCTION = 20167,
    CURLOPT_SEEKDATA = 10168,
    CURLOPT_CRLFILE,
    CURLOPT_ISSUERCERT,
    CURLOPT_ADDRESS_SCOPE = 171,
    CURLOPT_CERTINFO,
    CURLOPT_USERNAME = 10173,
    CURLOPT_PASSWORD,
    CURLOPT_PROXYUSERNAME,
    CURLOPT_PROXYPASSWORD,
    CURLOPT_NOPROXY,
    CURLOPT_TFTP_BLKSIZE = 178,
    CURLOPT_SOCKS5_GSSAPI_SERVICE = 10179,
    CURLOPT_SOCKS5_GSSAPI_NEC = 180,
    CURLOPT_PROTOCOLS,
    CURLOPT_REDIR_PROTOCOLS,
    CURLOPT_SSH_KNOWNHOSTS = 10183,
    CURLOPT_SSH_KEYFUNCTION = 20184,
    CURLOPT_SSH_KEYDATA = 10185,
    CURLOPT_MAIL_FROM,
    CURLOPT_MAIL_RCPT,
    CURLOPT_FTP_USE_PRET = 188,
    CURLOPT_RTSP_REQUEST,
    CURLOPT_RTSP_SESSION_ID = 10190,
    CURLOPT_RTSP_STREAM_URI,
    CURLOPT_RTSP_TRANSPORT,
    CURLOPT_RTSP_CLIENT_CSEQ = 193,
    CURLOPT_RTSP_SERVER_CSEQ,
    CURLOPT_INTERLEAVEDATA = 10195,
    CURLOPT_INTERLEAVEFUNCTION = 20196,
    CURLOPT_WILDCARDMATCH = 197,
    CURLOPT_CHUNK_BGN_FUNCTION = 20198,
    CURLOPT_CHUNK_END_FUNCTION,
    CURLOPT_FNMATCH_FUNCTION,
    CURLOPT_CHUNK_DATA = 10201,
    CURLOPT_FNMATCH_DATA,
    CURLOPT_RESOLVE,
    CURLOPT_TLSAUTH_USERNAME,
    CURLOPT_TLSAUTH_PASSWORD,
    CURLOPT_TLSAUTH_TYPE,
    CURLOPT_TRANSFER_ENCODING = 207,
    CURLOPT_CLOSESOCKETFUNCTION = 20208,
    CURLOPT_CLOSESOCKETDATA = 10209,
    CURLOPT_GSSAPI_DELEGATION = 210,
    CURLOPT_DNS_SERVERS = 10211,
    CURLOPT_ACCEPTTIMEOUT_MS = 212,
    CURLOPT_TCP_KEEPALIVE,
    CURLOPT_TCP_KEEPIDLE,
    CURLOPT_TCP_KEEPINTVL,
    CURLOPT_SSL_OPTIONS,
    CURLOPT_MAIL_AUTH = 10217,
    CURLOPT_SASL_IR = 218,
    CURLOPT_XFERINFOFUNCTION = 20219,
    CURLOPT_XOAUTH2_BEARER = 10220,
    CURLOPT_DNS_INTERFACE,
    CURLOPT_DNS_LOCAL_IP4,
    CURLOPT_DNS_LOCAL_IP6,
    CURLOPT_LOGIN_OPTIONS,
    CURLOPT_SSL_ENABLE_NPN = 225,
    CURLOPT_SSL_ENABLE_ALPN,
    CURLOPT_EXPECT_100_TIMEOUT_MS,
    CURLOPT_PROXYHEADER = 10228,
    CURLOPT_HEADEROPT = 229,
    CURLOPT_PINNEDPUBLICKEY = 10230,
    CURLOPT_UNIX_SOCKET_PATH,
    CURLOPT_SSL_VERIFYSTATUS = 232,
    CURLOPT_SSL_FALSESTART,
    CURLOPT_PATH_AS_IS,
    CURLOPT_PROXY_SERVICE_NAME = 10235,
    CURLOPT_SERVICE_NAME,
    CURLOPT_PIPEWAIT = 237,
    CURLOPT_DEFAULT_PROTOCOL = 10238,
    CURLOPT_STREAM_WEIGHT = 239,
    CURLOPT_STREAM_DEPENDS = 10240,
    CURLOPT_STREAM_DEPENDS_E,
    CURLOPT_TFTP_NO_OPTIONS = 242,
    CURLOPT_CONNECT_TO = 10243,
    CURLOPT_TCP_FASTOPEN = 244,
    CURLOPT_KEEP_SENDING_ON_ERROR,
    CURLOPT_PROXY_CAINFO = 10246,
    CURLOPT_PROXY_CAPATH,
    CURLOPT_PROXY_SSL_VERIFYPEER = 248,
    CURLOPT_PROXY_SSL_VERIFYHOST,
    CURLOPT_PROXY_SSLVERSION,
    CURLOPT_PROXY_TLSAUTH_USERNAME = 10251,
    CURLOPT_PROXY_TLSAUTH_PASSWORD,
    CURLOPT_PROXY_TLSAUTH_TYPE,
    CURLOPT_PROXY_SSLCERT,
    CURLOPT_PROXY_SSLCERTTYPE,
    CURLOPT_PROXY_SSLKEY,
    CURLOPT_PROXY_SSLKEYTYPE,
    CURLOPT_PROXY_KEYPASSWD,
    CURLOPT_PROXY_SSL_CIPHER_LIST,
    CURLOPT_PROXY_CRLFILE,
    CURLOPT_PROXY_SSL_OPTIONS = 261,
    CURLOPT_PRE_PROXY = 10262,
    CURLOPT_PROXY_PINNEDPUBLICKEY,
    CURLOPT_ABSTRACT_UNIX_SOCKET,
    CURLOPT_SUPPRESS_CONNECT_HEADERS = 265,
    CURLOPT_REQUEST_TARGET = 10266,
    CURLOPT_SOCKS5_AUTH = 267,
    CURLOPT_SSH_COMPRESSION,
    CURLOPT_MIMEPOST = 10269,
    CURLOPT_TIMEVALUE_LARGE = 30270,
    CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS = 271,
    CURLOPT_RESOLVER_START_FUNCTION = 20272,
    CURLOPT_RESOLVER_START_DATA = 10273,
    CURLOPT_HAPROXYPROTOCOL = 274,
    CURLOPT_DNS_SHUFFLE_ADDRESSES,
    CURLOPT_TLS13_CIPHERS = 10276,
    CURLOPT_PROXY_TLS13_CIPHERS,
    CURLOPT_DISALLOW_USERNAME_IN_URL = 278,
    CURLOPT_DOH_URL = 10279,
    CURLOPT_UPLOAD_BUFFERSIZE = 280,
    CURLOPT_UPKEEP_INTERVAL_MS,
    CURLOPT_CURLU = 10282,
    CURLOPT_TRAILERFUNCTION = 20283,
    CURLOPT_TRAILERDATA = 10284,
    CURLOPT_HTTP09_ALLOWED = 285,
    CURLOPT_ALTSVC_CTRL,
    CURLOPT_ALTSVC = 10287,
    CURLOPT_MAXAGE_CONN = 288,
    CURLOPT_SASL_AUTHZID = 10289,
    CURLOPT_MAIL_RCPT_ALLOWFAILS = 290,
    CURLOPT_SSLCERT_BLOB = 40291,
    CURLOPT_SSLKEY_BLOB,
    CURLOPT_PROXY_SSLCERT_BLOB,
    CURLOPT_PROXY_SSLKEY_BLOB,
    CURLOPT_ISSUERCERT_BLOB,
    CURLOPT_PROXY_ISSUERCERT = 10296,
    CURLOPT_PROXY_ISSUERCERT_BLOB = 40297,
    CURLOPT_SSL_EC_CURVES = 10298,
    CURLOPT_HSTS_CTRL = 299,
    CURLOPT_HSTS = 10300,
    CURLOPT_HSTSREADFUNCTION = 20301,
    CURLOPT_HSTSREADDATA = 10302,
    CURLOPT_HSTSWRITEFUNCTION = 20303,
    CURLOPT_HSTSWRITEDATA = 10304,
    CURLOPT_AWS_SIGV4,
    CURLOPT_DOH_SSL_VERIFYPEER = 306,
    CURLOPT_DOH_SSL_VERIFYHOST,
    CURLOPT_DOH_SSL_VERIFYSTATUS,
    CURLOPT_CAINFO_BLOB = 40309,
    CURLOPT_PROXY_CAINFO_BLOB,
    CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 = 10311,
    CURLOPT_PREREQFUNCTION = 20312,
    CURLOPT_PREREQDATA = 10313,
    CURLOPT_MAXLIFETIME_CONN = 314,
    CURLOPT_MIME_OPTIONS,
    CURLOPT_SSH_HOSTKEYFUNCTION = 20316,
    CURLOPT_SSH_HOSTKEYDATA = 10317,
    CURLOPT_PROTOCOLS_STR,
    CURLOPT_REDIR_PROTOCOLS_STR,
    CURLOPT_WS_OPTIONS = 320,
    CURLOPT_CA_CACHE_TIMEOUT,
    CURLOPT_QUICK_EXIT,
    CURLOPT_HAPROXY_CLIENT_IP = 10323,
    CURLOPT_SERVER_RESPONSE_TIMEOUT_MS = 324,
    CURLOPT_ECH = 10325,
    CURLOPT_TCP_KEEPCNT = 326,
    CURLOPT_UPLOAD_FLAGS,
    CURLOPT_SSL_SIGNATURE_ALGORITHMS = 10328,
} CURLoption;

typedef enum {
    CURLVERSION_FIRST,    /* 7.10 */
    CURLVERSION_SECOND,   /* 7.11.1 */
    CURLVERSION_THIRD,    /* 7.12.0 */
    CURLVERSION_FOURTH,   /* 7.16.1 */
    CURLVERSION_FIFTH,    /* 7.57.0 */
    CURLVERSION_SIXTH,    /* 7.66.0 */
    CURLVERSION_SEVENTH,  /* 7.70.0 */
    CURLVERSION_EIGHTH,   /* 7.72.0 */
    CURLVERSION_NINTH,    /* 7.75.0 */
    CURLVERSION_TENTH,    /* 7.77.0 */
    CURLVERSION_ELEVENTH, /* 7.87.0 */
    CURLVERSION_TWELFTH,  /* 8.8.0 */
    CURLVERSION_LAST      /* never actually use this */
} CURLversion;

typedef struct curl_version_info_data {
    CURLversion age;          /* age of the returned struct */
    const char* version;      /* LIBCURL_VERSION */
    unsigned int version_num; /* LIBCURL_VERSION_NUM */
    const char* host;         /* OS/host/cpu/machine when configured */
    int features;             /* bitmask, see defines below */
    const char* ssl_version;  /* human readable string */
    long ssl_version_num;     /* not used anymore, always 0 */
    const char* libz_version; /* human readable string */
    /* protocols is terminated by an entry with a NULL protoname */
    const char* const* protocols;

    /* The fields below this were added in CURLVERSION_SECOND */
    const char* ares;
    int ares_num;

    /* This field was added in CURLVERSION_THIRD */
    const char* libidn;

    /* These field were added in CURLVERSION_FOURTH */

    /* Same as '_libiconv_version' if built with HAVE_ICONV */
    int iconv_ver_num;

    const char* libssh_version; /* human readable string */

    /* These fields were added in CURLVERSION_FIFTH */
    unsigned int brotli_ver_num; /* Numeric Brotli version
                                    (MAJOR << 24) | (MINOR << 12) | PATCH */
    const char* brotli_version;  /* human readable string. */

    /* These fields were added in CURLVERSION_SIXTH */
    unsigned int nghttp2_ver_num; /* Numeric nghttp2 version
                                     (MAJOR << 16) | (MINOR << 8) | PATCH */
    const char* nghttp2_version;  /* human readable string. */
    const char* quic_version;     /* human readable quic (+ HTTP/3) library +
                                     version or NULL */

    /* These fields were added in CURLVERSION_SEVENTH */
    const char* cainfo; /* the built-in default CURLOPT_CAINFO, might
                           be NULL */
    const char* capath; /* the built-in default CURLOPT_CAPATH, might
                           be NULL */

    /* These fields were added in CURLVERSION_EIGHTH */
    unsigned int zstd_ver_num; /* Numeric Zstd version
                                    (MAJOR << 24) | (MINOR << 12) | PATCH */
    const char* zstd_version;  /* human readable string. */

    /* These fields were added in CURLVERSION_NINTH */
    const char* hyper_version; /* human readable string. */

    /* These fields were added in CURLVERSION_TENTH */
    const char* gsasl_version; /* human readable string. */

    /* These fields were added in CURLVERSION_ELEVENTH */
    /* feature_names is terminated by an entry with a NULL feature name */
    const char* const* feature_names;

    /* These fields were added in CURLVERSION_TWELFTH */
    const char* rtmp_version; /* human readable string. */
} curl_version_info_data;

typedef void CURLSH;

typedef enum {
    CURLSHE_OK,           /* all is fine */
    CURLSHE_BAD_OPTION,   /* 1 */
    CURLSHE_IN_USE,       /* 2 */
    CURLSHE_INVALID,      /* 3 */
    CURLSHE_NOMEM,        /* 4 out of memory */
    CURLSHE_NOT_BUILT_IN, /* 5 feature not present in lib */
    CURLSHE_LAST          /* never use */
} CURLSHcode;

typedef enum {
    CURL_LOCK_DATA_NONE = 0,
    CURL_LOCK_DATA_SHARE,
    CURL_LOCK_DATA_COOKIE,
    CURL_LOCK_DATA_DNS,
    CURL_LOCK_DATA_SSL_SESSION,
    CURL_LOCK_DATA_CONNECT,
    CURL_LOCK_DATA_PSL,
    CURL_LOCK_DATA_HSTS,
    CURL_LOCK_DATA_LAST
} curl_lock_data;

typedef enum {
    CURLSHOPT_NONE,       /* do not use */
    CURLSHOPT_SHARE,      /* specify a data type to share */
    CURLSHOPT_UNSHARE,    /* specify which data type to stop sharing */
    CURLSHOPT_LOCKFUNC,   /* pass in a 'curl_lock_function' pointer */
    CURLSHOPT_UNLOCKFUNC, /* pass in a 'curl_unlock_function' pointer */
    CURLSHOPT_USERDATA,   /* pass in a user data pointer used in the lock/unlock
                             callback functions */
    CURLSHOPT_LAST        /* never use */
} CURLSHoption;

typedef enum {
  CURLINFO_NONE, /* first, never use this */
  CURLINFO_EFFECTIVE_URL    = 0x100000 + 1,
  CURLINFO_RESPONSE_CODE    = 0x200000   + 2,
  CURLINFO_TOTAL_TIME       = 0x300000 + 3,
  CURLINFO_NAMELOOKUP_TIME  = 0x300000 + 4,
  CURLINFO_CONNECT_TIME     = 0x300000 + 5,
  CURLINFO_PRETRANSFER_TIME = 0x300000 + 6,
  CURLINFO_SIZE_UPLOAD_T    = 0x600000  + 7,
  CURLINFO_SIZE_DOWNLOAD_T  = 0x600000  + 8,
  CURLINFO_SPEED_DOWNLOAD_T = 0x600000  + 9,
  CURLINFO_SPEED_UPLOAD_T   = 0x600000  + 10,
  CURLINFO_HEADER_SIZE      = 0x200000   + 11,
  CURLINFO_REQUEST_SIZE     = 0x200000   + 12,
  CURLINFO_SSL_VERIFYRESULT = 0x200000   + 13,
  CURLINFO_FILETIME         = 0x200000   + 14,
  CURLINFO_FILETIME_T       = 0x600000  + 14,
  CURLINFO_CONTENT_LENGTH_DOWNLOAD_T = 0x600000  + 15,
  CURLINFO_CONTENT_LENGTH_UPLOAD_T   = 0x600000  + 16,
  CURLINFO_STARTTRANSFER_TIME = 0x300000 + 17,
  CURLINFO_CONTENT_TYPE     = 0x100000 + 18,
  CURLINFO_REDIRECT_TIME    = 0x300000 + 19,
  CURLINFO_REDIRECT_COUNT   = 0x200000   + 20,
  CURLINFO_PRIVATE          = 0x100000 + 21,
  CURLINFO_HTTP_CONNECTCODE = 0x200000   + 22,
  CURLINFO_HTTPAUTH_AVAIL   = 0x200000   + 23,
  CURLINFO_PROXYAUTH_AVAIL  = 0x200000   + 24,
  CURLINFO_OS_ERRNO         = 0x200000   + 25,
  CURLINFO_NUM_CONNECTS     = 0x200000   + 26,
  CURLINFO_SSL_ENGINES      = 0x400000  + 27,
  CURLINFO_COOKIELIST       = 0x400000  + 28,
  CURLINFO_FTP_ENTRY_PATH   = 0x100000 + 30,
  CURLINFO_REDIRECT_URL     = 0x100000 + 31,
  CURLINFO_PRIMARY_IP       = 0x100000 + 32,
  CURLINFO_APPCONNECT_TIME  = 0x300000 + 33,
  CURLINFO_CERTINFO         = 0x400000    + 34,
  CURLINFO_CONDITION_UNMET  = 0x200000   + 35,
  CURLINFO_RTSP_SESSION_ID  = 0x100000 + 36,
  CURLINFO_RTSP_CLIENT_CSEQ = 0x200000   + 37,
  CURLINFO_RTSP_SERVER_CSEQ = 0x200000   + 38,
  CURLINFO_RTSP_CSEQ_RECV   = 0x200000   + 39,
  CURLINFO_PRIMARY_PORT     = 0x200000   + 40,
  CURLINFO_LOCAL_IP         = 0x100000 + 41,
  CURLINFO_LOCAL_PORT       = 0x200000   + 42,
  CURLINFO_ACTIVESOCKET     = 0x500000 + 44,
  CURLINFO_TLS_SSL_PTR      = 0x400000    + 45,
  CURLINFO_HTTP_VERSION     = 0x200000   + 46,
  CURLINFO_PROXY_SSL_VERIFYRESULT = 0x200000 + 47,
  CURLINFO_SCHEME           = 0x100000 + 49,
  CURLINFO_TOTAL_TIME_T     = 0x600000 + 50,
  CURLINFO_NAMELOOKUP_TIME_T = 0x600000 + 51,
  CURLINFO_CONNECT_TIME_T   = 0x600000 + 52,
  CURLINFO_PRETRANSFER_TIME_T = 0x600000 + 53,
  CURLINFO_STARTTRANSFER_TIME_T = 0x600000 + 54,
  CURLINFO_REDIRECT_TIME_T  = 0x600000 + 55,
  CURLINFO_APPCONNECT_TIME_T = 0x600000 + 56,
  CURLINFO_RETRY_AFTER      = 0x600000 + 57,
  CURLINFO_EFFECTIVE_METHOD = 0x100000 + 58,
  CURLINFO_PROXY_ERROR      = 0x200000 + 59,
  CURLINFO_REFERER          = 0x100000 + 60,
  CURLINFO_CAINFO           = 0x100000 + 61,
  CURLINFO_CAPATH           = 0x100000 + 62,
  CURLINFO_XFER_ID          = 0x600000 + 63,
  CURLINFO_CONN_ID          = 0x600000 + 64,
  CURLINFO_QUEUE_TIME_T     = 0x600000 + 65,
  CURLINFO_USED_PROXY       = 0x200000 + 66,
  CURLINFO_POSTTRANSFER_TIME_T = 0x600000 + 67,
  CURLINFO_EARLYDATA_SENT_T = 0x600000 + 68,
  CURLINFO_HTTPAUTH_USED    = 0x200000 + 69,
  CURLINFO_PROXYAUTH_USED   = 0x200000 + 70,
  CURLINFO_LASTONE          = 70
} CURLINFO;

// Callback function types
typedef size_t (*write_callback)(
    char* contents, size_t size, size_t nmemb, void* userdata
);

// Functions
CURLcode curl_global_init(long flags);
CURL* curl_easy_init(void);
void curl_easy_cleanup(CURL* handle);
void curl_global_cleanup(void);
CURLcode curl_easy_setopt(CURL* curl, CURLoption option, ...);
const char* curl_easy_strerror(CURLcode errornum);
curl_version_info_data* curl_version_info(CURLversion);
CURLSH* curl_share_init(void);
CURLSHcode curl_share_cleanup(CURLSH* share);
CURLSHcode curl_share_setopt(CURLSH* share, CURLSHoption option, ...);
CURL* curl_easy_duphandle(CURL* handle);
CURLcode curl_easy_perform(CURL* easy_handle);
CURLcode curl_easy_getinfo(CURL* curl, CURLINFO info, ...);

// Debug functions
void abort(void);
